### ISSUE TITLE
LNS altitude not encoded properly

### ISSUE THREAD

**Issue by vincent290587** [RomainQuidet/LELocation-framework-iOS#2]
Hi Romain,

First I'd like to thank you for the amazing app.

I've noticed that the altitude seems not to be encoded properly.
Could you check and/or share the code you used to encode it ?

Many thanks

**Comment by RomainQuidet** [comment]
Hi,
Thanks for your feedbacks ! :)
I'll check and correct this tonight !

**Comment by RomainQuidet** [comment]
@vincent290587 Hi again. As per specification, the elevation is encoded on 3 bytes (sint24), with a precision of 1/100m.
I've checked my LE GPS app (transmitter), it encodes correctly the elevation. 
I've checked the LELocation framework (used by LE GPS Rec app), it decodes correctly the elevation, but there is a bug if you are using a transmitter GPS like the GL770, it then be always given as 0. I've corrected it, pushing soon a new version !

Is that ok for you? Did you have another issue with elevation?

**Comment by RomainQuidet** [comment]
LE GPS and LE GPS Rec app have been updated. Waiting for Apple review.

**Comment by vincent290587** [comment]
So you encode it as a signed int on 24 bits, with the first bit being the sign ?

In which order do you write the data, speed -> dist -> loc -> ele ?

**Comment by RomainQuidet** [comment]
Ha I don't have negative altitudes on my unit tests. Let me add that.
For the encoding, on transmitter side (LE GPS):
speed, (total distance is not coded yet), location, elevation, heading, ...

For the decoding, on LE GPS Rec and this framework:
speed, total distance (bytes are not read yet), location, elevation, heading ...

Do you have a binary sample of data to decode that you feel is wrongly decoded ? Which app do you use ?
Thanks !

**Comment by vincent290587** [comment]
I live in the Netherlands at an altitude of -1 / -2m ;-)
The thing troubling me is that when the altitude changes on my phone app, I don't see the data change on the service, instead I see 0xFF 0x01 0x10 where the altitude should be.
But I coded the service myself so I might have a bug myself.

**Comment by RomainQuidet** [comment]
pfff sint24 is pain to handle correctly. Anyway, this v1.5.1 should handle it, I added unit tests, it shows correct elevation. Let me know. I'm also pushing LE GPS and LE GPS Rec apps to Apple.

**Comment by vincent290587** [comment]
I'm using LE GPS only, but i'll let you know ASAP if that works

**Comment by RomainQuidet** [comment]
New version is out you can test it !

Romain

**Comment by vincent290587** [comment]
Tested and works ! Thanks again

**Comment by RomainQuidet** [comment]
Great !! Thanks to you :)

Romain
