### ISSUE TITLE
LNS time is local time

### ISSUE THREAD

**Issue by vincent290587** [RomainQuidet/LELocation-framework-iOS#3]
The transmitted time is the local time, but should be UTC time

**Comment by RomainQuidet** [comment]
you're right, same thing I'm updating that !

**Comment by RomainQuidet** [comment]
I've patched my LE GPS (transmitter) app, it was using local time.
I've patched this LELocation framework (used by LE GPS Rec app), as it was decoding the date as local time.
They both use now UTC :) Pushing the updates soon.
